strictness: veryhigh

pylint:
  options:
    max-line-length: 110
  disable:
    - too-many-instance-attributes
    - too-many-locals
    - too-few-public-methods
    - invalid-name
    - no-else-return
    - wrong-import-order

pep8:
  disable:
    - E501

mypy:
  run: True
  ignore-missing-import: True

mccabe:
  run: False

bandit:
  run: True
